name: ezpz-bci
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - mne==1.9.0
  - pandas
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - seaborn
  - psutil
  - pip:
    - brainflow
    - PySide6
    - torchsummary
